### ISSUE TITLE
GAME REVIEW

### ISSUE THREAD

**Issue by chilkacastro** [gbouzon/dragonRush#1]
**I REALLY REALLY LOVE YOUR GAME!!!! GREAT JOB!!**
**LOVE THE MENU SCREEN ESPECIALLY WHEN THE WORD TURNS FROM RED TO WHITE  :)**

**SUGGESTION:** (based on personal experience)
1. BE ABLE TO USE UP, DOWN, LEFT, AND RIGHT KEY IN LEVEL 2 AND 3 JUST LIKE LEVEL 1. 
both ASWD and UP/DOWN/LEFT/RIGHT works in level 1 so would it be possible to have that in level 2 and 3 as well -> maybe some players like me would find it convenient to use the up, down, left, right key together with the spacebar.

**Comment by gbouzon** [comment]
Thank you, that's very kind! I'll incorporate the arrow keys for the next version, thanks for reminding us :)
