### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by AtozZone** [gbouzon/dragonRush#2]
I really like the game, only one of the issues was understanding what the win condition is like you need to get a certain percentage but I dont know how to increase or how it will be decrease the percentage, nor what percentage will be considerate not "need more practice".

One think I like was the idea of game similarity between games I know and this one.

**Comment by gbouzon** [comment]
Thank you for the comment @AtozZone  ! I realize we're not very clear with the scoring system nor the percentage, so I'll see to fixing that.

There is no win condition. It was sort of a game to test how good you were in those types of games (which were games we played in our childhood). To increase the percentage, you have to get as many fruits and coins as possible and not let the enemies get near you. The message saying you need more practice would change if you got over 60%.
