### ISSUE TITLE
Game's Review

### ISSUE THREAD

**Issue by SamPham2020** [gbouzon/dragonRush#3]
I really like the feature which allows the dragon to spit fire, and it gave me drill when I first tried it. 
Also, as a programmer-wannabe, I learnt about a lot through your team's code and the way how you guys organized it. 

Here are some unfamiliar situations to me as a player: 
- There's a small instruction between each level. At first, I didn't know how to start that level, and I thought the screen was frozen.
- Sometimes, I just started the level 1 and died immediately because the enemy was so near to the starting spot. 
- Sometimes, the bomb was hidden under the fruit in level 2. I could never know it, and lost score. 

Overall, the game is great and very detailed. it's little bit hard for me, but I'm sure many people will like it.
Thank you

**Comment by gbouzon** [comment]
We will fix these bugs (if time allows). Thank you for the feedback!

**Comment by SamPham2020** [comment]
It's not really bugs. It's just my opinions as a game player.
